const TableData=[
    
    {id:2, fullName:"Rapsan Janid scscscs scscscs scscscs scscscs scscscs scscscs scscscs n jdsnjcndsj ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsvdsvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},
    {id:2, fullName:"Rapsan Janid ", age:26, city:"Noida", agse:26, cityc:"Noida", ciwy:"Patna", citxy:"Patna", citvy:"Patna",citvgy:"Patna",cvitvy:"Patna",citsvy:"Patna",citvsgy:"Patna",cvictvy:"Patna",citsvdy:"Patna",cditvsgy:"Patna",cvivctvy:"Patna",citsvrdy:"Patna",caitsvdy:"Patna",cditvvsgy:"Patna",cvivdctvy:"Patna",cistsvrdy:"Patna",caditvvsgy:"Patna",cvivdcctvy:"Patna",cistsverdy:"Patna"},

]
export default TableData;